# Generated by Django 6.0.6 on 2026-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="estoque",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade em Estoque"
            ),
        ),
    ]
