# Generated by Django 6.0.6 on 2026-06-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.CharField(
                default="Outros", max_length=100, verbose_name="Categoria"
            ),
        ),
    ]
