# Generated by Django 6.0.6 on 2026-06-24 14:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produtos", "0002_produto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 6, 24, 14, 54, 45, 960387, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Adicionado em",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Nota (1 a 5)",
                    ),
                ),
                (
                    "comentario",
                    models.TextField(blank=True, null=True, verbose_name="Comentário"),
                ),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="Produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-data_avaliacao"],
            },
        ),
    ]
